### ISSUE TITLE
 TypeError: global$1.XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by olifur** [DePayFi/web3-mock#18]
Hi, I am getting the following error when I try to run the advanced test from the `README.md`
https://github.com/DePayFi/web3-mock#advanced

```
e2etests_1  | TypeError: global$1.XMLHttpRequest is not a constructor
e2etests_1  | 
e2etests_1  |    at ../node_modules/@depay/solana-web3.js/dist/umd/index.js:12965
e2etests_1  | 
e2etests_1  |   12963 |         function checkTypeSupport(type) {
e2etests_1  |   12964 |           if (!xhr) {
e2etests_1  | > 12965 |             xhr = new global$1.XMLHttpRequest();
e2etests_1  |         |                   ^
e2etests_1  |   12966 |             // If location.host is empty, e.g. if this page/worker was loaded
e2etests_1  |   12967 |             // from a Blob, then use example.com to avoid an error
e2etests_1  |   12968 |             xhr.open('GET', global$1.location.host ? '/' : 'https://example.com');
e2etests_1  | 
e2etests_1  |     at checkTypeSupport (/app/node_modules/@depay/solana-web3.js/dist/umd/index.js:12965:12)
e2etests_1  |     at /app/node_modules/@depay/solana-web3.js/dist/umd/index.js:12984:39
e2etests_1  |     at /app/node_modules/@depay/solana-web3.js/dist/umd/index.js:2:65
e2etests_1  |     at Object.<anonymous> (/app/node_modules/@depay/solana-web3.js/dist/umd/index.js:5:3)
e2etests_1  |     at /app/node_modules/@depay/web3-mock/dist/umd/index.js:2:174
e2etests_1  |     at Object.<anonymous> (/app/node_modules/@depay/web3-mock/dist/umd/index.js:5:2)
```

I am using the following environment

```
node --version
v16.15.1
# npm --version
8.11.0
grep @depay package.json 
    "@depay/web3-blockchains": "^5.0.2",
    "@depay/web3-mock": "^13.6.4"
Working on Linux docker

```

**Comment by spape** [comment]
can you try the following:

```
yarn add cross-fetch --dev
```

and add the following to your jest setup file:

```
import fetch from 'cross-fetch'
global.fetch = fetch
```

and let me know if that works or not?

**Comment by spape** [comment]
I've also just noticed that the readme was missing the fact that you need to install this as a dev dependency (just fixed it)...

can you uninstall it again and install it properly as a dev dependency: https://github.com/DePayFi/web3-mock#quickstart

**Comment by olifur** [comment]
Hi,

still the same issue after I applied the `cross-fetch` module.

Please note that I am not using jest but playwright. Maybe its an issue with it.

**Comment by olifur** [comment]
If I apply solution from here `https://stackoverflow.com/a/59214301/1958795` using 
```
global.XMLHttpRequest = require('xhr2');
```

I get past this problem but facing the next:

```
e2etests_1  | 
e2etests_1  | Running 0 test using 0 worker
e2etests_1  | 
e2etests_1  | 
e2etests_1  | TypeError: Cannot read properties of undefined (reading 'host')
e2etests_1  | 
e2etests_1  |    at ../node_modules/@depay/solana-web3.js/dist/umd/index.js:12968
e2etests_1  | 
e2etests_1  |   12966 |             // If location.host is empty, e.g. if this page/worker was loaded
e2etests_1  |   12967 |             // from a Blob, then use example.com to avoid an error
e2etests_1  | > 12968 |             xhr.open('GET', global$1.location.host ? '/' : 'https://example.com');
e2etests_1  |         |                                               ^
e2etests_1  |   12969 |           }
e2etests_1  |   12970 |           try {
e2etests_1  |   12971 |             xhr.responseType = type;
e2etests_1  | 
e2etests_1  |     at checkTypeSupport (/app/node_modules/@depay/solana-web3.js/dist/umd/index.js:12968:40)
e2etests_1  |     at /app/node_modules/@depay/solana-web3.js/dist/umd/index.js:12984:39
e2etests_1  |     at /app/node_modules/@depay/solana-web3.js/dist/umd/index.js:2:65
e2etests_1  |     at Object.<anonymous> (/app/node_modules/@depay/solana-web3.js/dist/umd/index.js:5:3)
e2etests_1  |     at /app/node_modules/@depay/web3-mock/dist/umd/index.js:2:174
e2etests_1  |     at Object.<anonymous> (/app/node_modules/@depay/web3-mock/dist/umd/index.js:5:2)
e2etests_1  | 
e2etests_1  | =================
e2etests_1  |  no tests found.
e2etests_1  | =================
e2etests_1  | 

```

**Comment by spape** [comment]
both errors indicate that either playwright does not support browser based libraries, which I doubt after checking what it is, or you are missing some kind of default mock for things like global.location (alias window.location) and XMLHttpRequest.

**Comment by spape** [comment]
you could also try 
```
global = window
```
wherever you've set `global.XMLHttpRequest = require('xhr2');`

**Comment by olifur** [comment]
do you know if `web3-mock` works in combination with other e2e test frameworks like `cypress`?

**Comment by spape** [comment]
works perfectly fine with cypress (example: https://github.com/DePayFi/widgets/blob/master/cypress/e2e/Payment/main.js) and jest (example: https://github.com/DePayFi/web3-payments/blob/master/tests/units/polygon/fee.spec.js)

**Comment by spape** [comment]
can you try a version before we introduced solana, e.g. `v12.1.0` ?

**Comment by olifur** [comment]
Ok, thank you. I will stick to Cypress then.
Case can be closed.

**Comment by spape** [comment]
certainly give `v12.1.0` a try. It could still be that the solana introduction caused the problem which didnt make it to the examples yet.

**Comment by olifur** [comment]
`v12.1.0` is working fine with playwright!

**Comment by spape** [comment]
actually we already introduced solana in v12 but we added some additional solana libraries in v13.

If you're not building on Solana I suggest you stick with `v11.11.0` and stick with the v11 readme: 

https://github.com/DePayFi/web3-mock/blob/daa940851a1526726f2021df80746d7c83cf6bb3/README.md

We will make sure to fix v13 in the meantime.

**Comment by spape** [comment]
I've just released 13.7.0 which is fixing this issue and adds support for playwright

https://github.com/DePayFi/web3-mock/releases/tag/v13.7.0

Make sure you migrate to the 12+ syntax to mock requests (it's `mock({request: ...})` and not `mock({call: ...})` anymore).

**Comment by JDansercoer** [comment]
I just had the same issue. 

After hours of trying to find out why my set up won't work but the example here does, I finally found out that you added 

```
// web3-mock polyfills:
global.XMLHttpRequest = require('xhr2')
global.location = { host: undefined }
```

to `playwright.config.(t/j)s`.

Might want to add that to the Readme too, no?

**Comment by 10xSebastian** [comment]
It is already part of the readme: https://github.com/DePayFi/web3-mock#playwright
🤔

**Comment by JDansercoer** [comment]
Oh I totally missed that. I'd either move important stuff like that to the top or provide a TOC at the beginning?

**Comment by 10xSebastian** [comment]
Good Idea. Will add it to the first section: "Quickstart". Github creates and provides TOC itself by now.

![Screenshot 2022-09-30 at 15 26 11](https://user-images.githubusercontent.com/851393/193279743-9e908061-b0f6-42b9-9015-09a8fa4fbebc.png)

Thanks for the feedback 🙏

**Comment by 10xSebastian** [comment]
Added to quickstart: https://github.com/DePayFi/web3-mock/blob/main/README.md#quickstart

**Comment by JDansercoer** [comment]
Thanks for the quick response man 🙏
