### ISSUE TITLE
Support for Goerli

### ISSUE THREAD

**Issue by JDansercoer** [DePayFi/web3-mock#27]
Our application currently has only been launched (to the public even) on the Goerli chain. Our app requires users to be on Goerli to ensure the correct working. To ensure that, we have a modal that can not be closed unless you're on the correct chain.

However, this is blocking us from testing with this library, as I can't figure out how to make the mock act like the test is running on Goerli.

Any advice?

**Comment by 10xSebastian** [comment]
You could add Goerli to https://github.com/DePayFi/web3-blockchains in order to have it available for web3-mock, too.
