### ISSUE TITLE
Support EVMOS Chain

### ISSUE THREAD

**Issue by sandoche** [DePayFi/web3-mock#30]
Is it possible to add support for Evmos which is an EVM chain?
Here are the infos: https://chainlist.org/chain/9001

**Comment by 10xSebastian** [comment]
Yes it's possible.

It just needs to be added to the underlying libraries first in the following order:

1. https://github.com/DePayFi/web3-blockchains
2. https://github.com/DePayFi/web3-client
3. https://github.com/DePayFi/web3-tokens

That said. We are currently not interested in adding it ourselves.
