### ISSUE TITLE
Does not work properly with wagmi 

### ISSUE THREAD

**Issue by pociej** [DePayFi/web3-mock#32]
When follow mocking connection 

```

mock({
  blockchain : 'ethereum',
  accounts: {
    return: ['0xd8da6bf26964af9d7eed9e03e53415d37aa96045']
  }
})

 config = createConfig({
  autoConnect: true,
  publicClient: createPublicClient({
    chain: mainnet,
    transport: custom(window.ethereum),
  }),
})
```

and then try to check currently connected network byt `useNetwork` hook it keeps returning undefined as well as `const { isConnected, address } = useAccount()` gives respectively `false` and `undefined`.

**Comment by 0xNe0x1** [comment]
sorry, but wagmi if officially not supported.
