### ISSUE TITLE
Cannot call cy.window() outside a running test.

### ISSUE THREAD

**Issue by blassaut** [DePayFi/web3-mock#38]
Hello guys,

I am getting this `Cannot call cy.window() outside a running test.` error with cypress 13.14.2 when I want to test web3-mock.

Here is the simple code:

```typescript
import { Given, When, Then, Before } from '@badeball/cypress-cucumber-preprocessor';
import { mock, resetMocks } from '@depay/web3-mock';

const blockchain = 'ethereum';
const accounts = ['0xd8da6bf26964af9d7eed9e03e53415d37aa96045'];

Before(() => {
  resetMocks();
  mock({
    blockchain,
    accounts: {
      delay: 10000, // ms
      return: accounts
    }
  });
});

Given('I visit the dapp', () => {
  cy.visit('https://metamask.github.io/test-dapp/');
});
```

Would you have any idea why I am getting this? I'm sure I'm forgetting some configuration somewhere (I'm using typescript with Cucumber). FYI, I also tried without Cucumber in a single typescript/javascript file with describe/it as well, without success.

**Comment by 0xNe0x1** [comment]
Hi 👋 

You could try to move the `resetMocks` and `mock` into the `Given`, just to see if cy.window is available then.

**Comment by blassaut** [comment]
Yes @0xNe0x1 , also tried this withtout success.
