### ISSUE TITLE
Support for signTypedData

### ISSUE THREAD

**Issue by dmlayton** [DePayFi/web3-mock#8]
Thanks for this project! I'm trying to write cypress tests and Metamask was being a pain. 

I'm getting `Web3Mock request: Unknown request method eth_signTypedData_v4!`
looks like it's just not a supported [case](https://github.com/DePayFi/web3-mock/blob/66fcaf82e4a21990081e1c24a29afbfe1ec73d3a/src/vms/evm/request.js#L83)

**Comment by spape** [comment]
Correct, we don't support signatures for structured data, yet.

Feel free to add it or to fund it via https://gitcoin.co 🙏

**Comment by dmlayton** [comment]
Pull request #9

**Comment by dmlayton** [comment]
Created a new pull request #10 with the requested documentation and test.

**Comment by spape** [comment]
https://github.com/DePayFi/web3-mock/releases/tag/v11.1.0
